# Generated by Django 4.1.3 on 2022-12-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="create_at", new_name="created_at",
        ),
    ]
