# Generated by Django 4.1.3 on 2022-12-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_replying_to_reply_post_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply", old_name="post_id", new_name="replying_to",
        ),
    ]
