# Generated by Django 4.1.3 on 2022-12-12 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_wallet_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nonce",
            field=models.CharField(default=users.models.generate_nonce, max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(
                db_index=True, default="", max_length=42, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(max_length=160)),
                ("name", models.CharField(max_length=50)),
                ("profile_url", models.CharField(max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
