# Generated by Django 4.1.3 on 2022-12-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_profile_pics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="profile_pics", new_name="profile_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="banner_url",
            field=models.ImageField(
                default="banner_default.png", upload_to="banner_pics"
            ),
        ),
    ]
