# Generated by Django 4.1.3 on 2022-12-13 03:22

from django.db import migrations, models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_profile_pics_profile_profile_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="new_user", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="banner_url",
            field=models.ImageField(
                default="banner_default.png",
                storage=users.storage.OverwriteStorage(),
                upload_to="banner_pics",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_url",
            field=models.ImageField(
                default="default.png",
                storage=users.storage.OverwriteStorage(),
                upload_to="profile_pics",
            ),
        ),
    ]
