# Generated by Django 4.1.3 on 2022-12-13 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_new_user_alter_profile_banner_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="new_user",),
    ]
