# Generated by Django 4.1.3 on 2022-12-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_new_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="new_user", field=models.BooleanField(default=True),
        ),
    ]
