# Generated by Django 4.1.3 on 2022-12-24 15:16

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_new_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with this username already exists."},
                max_length=15,
                unique=True,
                validators=[users.validators.validate_username],
            ),
        ),
    ]
